### ISSUE TITLE
USB 3.0 Not working on Catalina 10.15.x

### ISSUE THREAD

**Issue by d4vinder** [d4vinder/HP-Z620-Hackintosh-macOS-Catalina#1]
The Texas instruments USB 3.0 ports are not working. To circumvent this use PCI USB 3.0/1 cards such as [this one](https://www.amazon.co.uk/gp/product/B0773KH3ZR/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1). Works natively with OSx, see image below. 

I'd be interested to know if anyone knows a way of getting the TUSBX 3.0 bus working at USB 3.0 speeds.

![Screenshot 2020-05-02 at 08 09 30](https://user-images.githubusercontent.com/30625034/80857796-a2813000-8c4c-11ea-849b-411f338a9f96.png)

**Comment by mokiii** [comment]
https://github.com/mokiii/HP-Z620-Hackintosh-macOS_10.13-10.15

**Comment by d4vinder** [comment]
Does your USB work natively at 3.0 speeds? 

UPDATE: I tried your efi on Catalina 10.15.5, it did not run the usb 3.0 ports at usb 3.0 speeds. The Texas Instruments USB 3.0 bus doesn’t show in the hardware section.

**Comment by mokiii** [comment]
> Does your USB work natively at 3.0 speeds?
> 
> UPDATE: I tried your efi on Catalina 10.15.5, it did not run the usb 3.0 ports at usb 3.0 speeds. The Texas Instruments USB 3.0 bus doesn’t show in the hardware section.

I only tested to 10.15.4

**Comment by d4vinder** [comment]
@mokiii how did you define the TI USB controller? I cannot get it to work even with your config.

**Comment by d4vinder** [comment]
Thanks Mokii. Finally got around to applying some of your work. CPU power management now works great! Many Thanks.
