### ISSUE TITLE
Installation Drive not showing

### ISSUE THREAD

**Issue by ghost** [d4vinder/HP-Z620-Hackintosh-macOS-Catalina#2]
As the title says when I open Disk Utility the installation drive does not show. 

Also I tried with removing the internal drive and using one of the rear USB 2.0's to test it, and it gave me the message "Can't install MacOS Mojave, keeps saying firmware partition missing."

**Comment by d4vinder** [comment]
This guide is for Catalina As per the title. I have not tested this build on Mojave.

**Comment by ghost** [comment]
I apologize about this, Mojave was a typo and it was Catalina. Can this case be reopened? I'll give it another shot once I have time to do it and get better documentation. Thanks.

**Comment by d4vinder** [comment]
I've updated the BIOS Settings. See if that helps.
