### ISSUE TITLE
Can you help with CPUpowermanagement? 

### ISSUE THREAD

**Issue by saitek1710** [d4vinder/HP-Z620-Hackintosh-macOS-Catalina#6]
Hi, im using e5 2696 v2. However, it stucks at the base speed. how would you utilise the boost speed on your pc? 

I use your efi, the hackintosh has been done succesfully. however, the boot loading pretty long. Do you have the same problem? what have you change?

**Comment by d4vinder** [comment]
Your boot times should be pretty quick, what does the Clover bootlog report? 

For your CpuPm, try this: 

Add this to Clover Configurator >> Kernel and Kexts Patches >> KextsToPatch: 

**Name**: com.apple.driver.AppleIntelCPUPowerManagement
**Find**: D0050000 84C07446 E8
**Replace**: D0050000 84C0EB46 E8

**Comment by saitek1710** [comment]
Hi D4vinder,

Thank you for your reply. 

I attached my bootlog report. Would you take a look ? 

I appreciate your help

Regards.

[z620 e5 269699v2.txt](https://github.com/d4vinder/HP-Z620-Hackintosh-macOS-Catalina/files/4849436/z620.e5.269699v2.txt)

**Comment by d4vinder** [comment]
Try the latest upload of the EFI.zip file. It has a the EMU driver removed that has improved performance (and your should improve your boot-times) on the system. 

It would seem the MSR lock is applied. Short of modding the bios, there doesn't seem to find a way of unlocking it on Catalina to allow for Turbo boost.

**Comment by d4vinder** [comment]
The power management issue is resolved. try the latest EFI folder.
